### ISSUE TITLE
Differenciate between Person and Organization when relating an agent to an activity

### ISSUE THREAD

**Issue by tfrancart** [ArchivesNationalesFR/rico-converter#17]
> différencier pour les relations entre l’agent et une activité, le cas des personnes et le cas des
organismes

**Comment by tfrancart** [comment]
@florenceclavaud can you please update the unit tests for this as I don't clearly see what needs to be changed ? Thanks

**Comment by florenceclavaud** [comment]
I have begun to work on this, and so I have modified the expected.xml file for the _22occupation test. Both unit tests (about occupations and functions) still have to be modified, in order to add the rico:performsOrPerformed shortcuts: just like for the Mandate case mentioned in a comment on issue #5, the target activities will always be blank nodes. So we need to generate a rdf:nodeID for these activities, and to reuse them for the shortcut.

**Comment by tfrancart** [comment]
Unit test OK, to be finalised and create PR

**Comment by tfrancart** [comment]
This is done and can be reviewed in #41
