### ISSUE TITLE
Process values of XML attribute "otherlevel" when level="otherlevel"

### ISSUE THREAD

**Issue by tfrancart** [ArchivesNationalesFR/rico-converter#33]
See #10

**Comment by tfrancart** [comment]
Florence to check the values of that attribute and create unit tests

**Comment by florenceclavaud** [comment]
i @tfrancart, I have had a quick look at the whole corpus of our about 31000 finding aids (dated March 2022) and found 15605 otherlevel attributes with 47 different values, among which a few silly ones, a few odd ones, and many others that include at least:
-  one of the following strings: 
dossier | fonds | serie | série | articles | groupe-de-pieces | collection | subgrp | sbgrp
which means that the description unit is a rico:RecordSet.
- or one of the following strings:
page-de-titre  | groupe-de-page | groupes-de-page | groupe-depage
which means that the description unit is a rico:RecordPart.

So I think we could try and take these values into account, maybe in params like the OTHERLEVEL_RECORDSET_PATTERN you created in the latest release (commit https://github.com/ArchivesNationalesFR/rico-converter/commit/4a3599b60b38e4e5a06b0f7e7c832ea3656e2257), or in keywords file like the eac2rico-keywords.xml file, so that this can be modified later on by the users of the tool. I suspect that the ANF are not the only institution that uses @otherlevel with free values, at least in France. Anyway at the ANF, we will need time to check and standardize these values.

**Comment by florenceclavaud** [comment]
Another suggestion: in the log files, would it be possible to output, not only the id of the finding aid, but also the id (c/@id) of the description unit, for such warnings? it would help find the description unit concerned (particularly about @otherlevel, or when there is no @level attribute for example).

**Comment by tfrancart** [comment]
@florenceclavaud : I have moved the OTHERLEVEL_RECORDSET_PATTERN, as well as all other XSLT parameters in the main.xslt (for EAD and EAC). This allows to easily modify them without touching the large XSLT(s). I have also adjusted the otherlevel pattern to match your value.

I still need to see what can be done regarding the RecordPart

**Comment by florenceclavaud** [comment]
HI @tfrancart, I can create the unit tests for both Record Sets and Record Parts.

**Comment by tfrancart** [comment]
Inclure telle quelle la valeur de otherlevel dans dc:type systématiquement, pour RecordSet et RecordPart.
Faire un test unitaire 15d_RecordPart pour tester ce cas
On laisse rico:hasOrHadPart dans le cas où c'est un RecordPart

**Comment by florenceclavaud** [comment]
HI @tfrancart, just to say that the EGAD subteam that develops RiC-O has made the decision to make rico:includesOrIncluded a subproperty of rico:hasOrHadPart (see https://github.com/ICA-EGAD/RiC-O/issues/55). So we can use hasOrHadPart to connect the record resource to a component when we do not know if it is a Record Set or a Record. And keep the more precise subproperties, includesOrIncluded, and hasOrHadConstituent, when we know what we have.

**Comment by tfrancart** [comment]
@florenceclavaud this is implemented and can be reviewed in PR #43
