### ISSUE TITLE
Check for proper URL format (encoding, spaces) whe nconverting

### ISSUE THREAD

**Issue by tfrancart** [ArchivesNationalesFR/rico-converter#7]

**Comment by tfrancart** [comment]
Potential problems in EAC : eac:cpfRelation[@cpfRelationType = 'identity'] : add an encodeForUrl function.
And EAD in otherFindAid. Forence to check for more examples

**Comment by tfrancart** [comment]
- Function  URI-cpfRelationIdentity used from eac:cpfRelation[@cpfRelationType = 'identity'] : I can't add an encode-for-uri otherwise the generated URL will simply be invalid. I could remove the spaces, but that's all I can do.
- otherFindAid : right now I can't see where it could possibly break. It is hard to fix without concrete examples/situations/tests. Nothing done ATM.

**Comment by tfrancart** [comment]
Intégrer https://www.w3.org/2011/04/XMLSchema/TypeLibrary-IRI-RFC3987.xsd#type_IRI-reference-3987, à mettre dans le otherwise, et si l'URI ne matche pas, on sort un warning.

**Comment by tfrancart** [comment]
@florenceclavaud trouve les cas de test pour `otherfindaid`

**Comment by florenceclavaud** [comment]
Hi @tfrancart, I have looked for, in the whole of our EAC files, the values of `//cpfRelation[@cpfRelationType='identity']/@xlink:href` when they do not start with `http`.
We actually have there a few odd URIs (though a validation against the EAC-CPF scheme gives no error, since their type is xsd:anyURI which is quite permissive), which can be categorized as follows:

- plain text, containing spaces and non ASCII characters, and resulting from a wrong human action, e.g.: `<cpfRelation xmlns:xlink="http://www.w3.org/1999/xlink" cpfRelationType="identity" xlink:href="École française d'Athènes" xlink:type="simple">`

- first segment not present or incomplete, e.g.:
`<cpfRelation xmlns:xlink="http://www.w3.org/1999/xlink" cpfRelationType="identity" xlink:href="ark:/12148/cb11877582c" xlink:type="simple">`
`<cpfRelation xmlns:xlink="http://www.w3.org/1999/xlink" cpfRelationType="identity" xlink:href="maitron.fr/spip.php?article17968" xlink:type="simple">`
`<cpfRelation xmlns:xlink="http://www.w3.org/1999/xlink" cpfRelationType="identity" xlink:href="www.wikidata.org/entity/Q55849612" xlink:type="simple">`

Both categories are already covered by the XSLT that converts the EAC files, as it only takes into account the values that start with 'http'.

There also are a few cases like the following ones that start with 'http' and include spaces, and that obviously result from a bad copy/paste action:
`<cpfRelation xmlns:xlink="http://www.w3.org/1999/xlink" cpfRelationType="identity" xlink:href="http://catalogue.bnf.fr/ark:/12148/cb11946440gNey, Michel (1769-1815)" xlink:type="simple">`
`<cpfRelation xmlns:xlink="http://www.w3.org/1999/xlink" cpfRelationType="identity" xlink:href="https://www.idref.fr/032603444Copier cet identifiant (PPN)" xlink:type="simple">`

I will make sure that the few EAC files concerned are corrected, but new cases may occur till we have not, in our local system, better validation constraints. 
Anyway, all these cases are well covered by the XSLT (provided that there is a space in the value). And it is not up to RiC-O Converter to anticipate any possible wrong value - not to mention the possibly false identity assertions stored.

I think that, considering the way these attributes are filled (mainly by colleagues, not automatically), __we should also consider the possibility that the value ends with a dot__ (after applying normalize-space()). For now there is no case of the kind in the EAC files, but there are some @href values ending with a dot in the EAD files (I will add a new comment on this), so...
That's all I have in mind for the EAC files.
What do you think?
